name: Deploy on Home Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted  # <--- ВАЖНО: меняем ubuntu-latest на self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update and Restart Docker
        run: |
          docker compose up -d --build --remove-orphans
          docker image prune -f