name: Deploy to Server

on:
  push:
    branches:
      - main  # Срабатывает при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /depeg-bot
            
            git pull origin main

            docker compose up -d --build --remove-orphans
            
            docker image prune -f
            
            echo "Deployment successful!"